name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - id: go-version
        run: echo "version=$(cat ./.go-version)" >> $GITHUB_OUTPUT

  terraform-provider-release:
    name: 'Terraform Provider Release'
    runs-on: ubuntu-latest
    needs: [go-version]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.version }}
      - name: Import GPG key
        run: |
          echo -n "$GPG_PRIVATE_KEY" | gpg --batch --no-tty --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_GPG_KEY }}
      - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: "5C468778062D87BF!"
